import { Ticket } from "@/types/tickets";

export const tickets: Ticket[] = [
  {
    id: "1",
    protocolo: "20230001",
    entrada: new Date("2023-01-10"),
    hora: "09:15",
    sistema: "Sistema A",
    serventia: "Serventia Central",
    codigo: "COD-001",
    prazo: "5 dias",
    ultimaAtualizacao: new Date("2023-01-12"),
    responsavel: "João Silva",
    diasAtras: 0,
    title: "Problema de login",
    description: "Usuário não consegue acessar o sistema",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2023-01-12"),
  },
  {
    id: "2",
    protocolo: "20230002",
    entrada: new Date("2023-01-11"),
    hora: "14:30",
    sistema: "Sistema B",
    serventia: "Serventia Norte",
    codigo: "COD-002",
    prazo: "3 dias",
    ultimaAtualizacao: new Date("2023-01-15"),
    responsavel: "Maria Souza",
    diasAtras: 2,
    title: "Erro no relatório",
    description: "Relatório está gerando dados incorretos",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-11"),
    updatedAt: new Date("2023-01-15"),
  },
  {
    id: "3",
    protocolo: "20230003",
    entrada: new Date("2023-01-12"),
    hora: "10:45",
    sistema: "Sistema C",
    serventia: "Serventia Sul",
    codigo: "COD-003",
    prazo: "7 dias",
    ultimaAtualizacao: new Date("2023-01-18"),
    responsavel: "Carlos Oliveira",
    diasAtras: 0,
    title: "Atualização de cadastro",
    description: "Necessário atualizar dados cadastrais",
    status: "closed",
    priority: "low",
    createdAt: new Date("2023-01-12"),
    updatedAt: new Date("2023-01-18"),
  },
  {
    id: "4",
    protocolo: "20230004",
    entrada: new Date("2023-01-13"),
    hora: "16:20",
    sistema: "Sistema A",
    serventia: "Serventia Leste",
    codigo: "COD-004",
    prazo: "2 dias",
    ultimaAtualizacao: new Date("2023-01-16"),
    responsavel: "Ana Paula",
    diasAtras: 1,
    title: "Sistema lento",
    description: "Sistema está respondendo lentamente",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-13"),
    updatedAt: new Date("2023-01-16"),
  },
  {
    id: "5",
    protocolo: "20230005",
    entrada: new Date("2023-01-14"),
    hora: "11:10",
    sistema: "Sistema B",
    serventia: "Serventia Oeste",
    codigo: "COD-005",
    prazo: "4 dias",
    ultimaAtualizacao: new Date("2023-01-17"),
    responsavel: "Pedro Santos",
    diasAtras: 0,
    title: "Problema com impressão",
    description: "Não está imprimindo corretamente",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-14"),
    updatedAt: new Date("2023-01-17"),
  },
  {
    id: "6",
    protocolo: "20230006",
    entrada: new Date("2023-01-15"),
    hora: "08:45",
    sistema: "Sistema C",
    serventia: "Serventia Central",
    codigo: "COD-006",
    prazo: "5 dias",
    ultimaAtualizacao: new Date("2023-01-20"),
    responsavel: "Fernanda Lima",
    diasAtras: 0,
    title: "Cadastro duplicado",
    description: "Registros estão sendo duplicados no sistema",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "7",
    protocolo: "20230007",
    entrada: new Date("2023-01-16"),
    hora: "13:25",
    sistema: "Sistema A",
    serventia: "Serventia Norte",
    codigo: "COD-007",
    prazo: "3 dias",
    ultimaAtualizacao: new Date("2023-01-19"),
    responsavel: "Ricardo Alves",
    diasAtras: 0,
    title: "Erro na busca",
    description: "Filtro de busca não está funcionando",
    status: "closed",
    priority: "low",
    createdAt: new Date("2023-01-16"),
    updatedAt: new Date("2023-01-19"),
  },
  {
    id: "8",
    protocolo: "20230008",
    entrada: new Date("2023-01-17"),
    hora: "15:50",
    sistema: "Sistema B",
    serventia: "Serventia Sul",
    codigo: "COD-008",
    prazo: "6 dias",
    ultimaAtualizacao: new Date("2023-01-23"),
    responsavel: "Juliana Costa",
    diasAtras: 0,
    title: "Atualização necessária",
    description: "Precisa atualizar versão do sistema",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-17"),
    updatedAt: new Date("2023-01-23"),
  },
  {
    id: "9",
    protocolo: "20230009",
    entrada: new Date("2023-01-18"),
    hora: "10:30",
    sistema: "Sistema C",
    serventia: "Serventia Leste",
    codigo: "COD-009",
    prazo: "2 dias",
    ultimaAtualizacao: new Date("2023-01-20"),
    responsavel: "Marcos Antonio",
    diasAtras: 0,
    title: "Problema com email",
    description: "Não está recebendo emails do sistema",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-18"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "10",
    protocolo: "20230010",
    entrada: new Date("2023-01-19"),
    hora: "09:05",
    sistema: "Sistema A",
    serventia: "Serventia Oeste",
    codigo: "COD-010",
    prazo: "4 dias",
    ultimaAtualizacao: new Date("2023-01-23"),
    responsavel: "Patricia Gomes",
    diasAtras: 0,
    title: "Relatório mensal",
    description: "Gerar relatório mensal de atividades",
    status: "closed",
    priority: "low",
    createdAt: new Date("2023-01-19"),
    updatedAt: new Date("2023-01-23"),
  },
  {
    id: "11",
    protocolo: "20230011",
    entrada: new Date("2023-01-20"),
    hora: "14:15",
    sistema: "Sistema B",
    serventia: "Serventia Central",
    codigo: "COD-011",
    prazo: "5 dias",
    ultimaAtualizacao: new Date("2023-01-25"),
    responsavel: "Lucas Martins",
    diasAtras: 0,
    title: "Erro na importação",
    description: "Dados não estão sendo importados corretamente",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-25"),
  },
  {
    id: "12",
    protocolo: "20230012",
    entrada: new Date("2023-01-21"),
    hora: "11:40",
    sistema: "Sistema C",
    serventia: "Serventia Norte",
    codigo: "COD-012",
    prazo: "3 dias",
    ultimaAtualizacao: new Date("2023-01-24"),
    responsavel: "Amanda Ribeiro",
    diasAtras: 0,
    title: "Problema com senha",
    description: "Usuário não consegue alterar senha",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-21"),
    updatedAt: new Date("2023-01-24"),
  },
  {
    id: "13",
    protocolo: "20230013",
    entrada: new Date("2023-01-22"),
    hora: "16:55",
    sistema: "Sistema A",
    serventia: "Serventia Sul",
    codigo: "COD-013",
    prazo: "7 dias",
    ultimaAtualizacao: new Date("2023-01-29"),
    responsavel: "Roberto Ferreira",
    diasAtras: 0,
    title: "Atualização de dados",
    description: "Sincronizar dados com sistema externo",
    status: "closed",
    priority: "low",
    createdAt: new Date("2023-01-22"),
    updatedAt: new Date("2023-01-29"),
  },
  {
    id: "14",
    protocolo: "20230014",
    entrada: new Date("2023-01-23"),
    hora: "08:30",
    sistema: "Sistema B",
    serventia: "Serventia Leste",
    codigo: "COD-014",
    prazo: "2 dias",
    ultimaAtualizacao: new Date("2023-01-25"),
    responsavel: "Carla Mendes",
    diasAtras: 0,
    title: "Erro no cálculo",
    description: "Cálculo está com resultado incorreto",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-23"),
    updatedAt: new Date("2023-01-25"),
  },
  {
    id: "15",
    protocolo: "20230015",
    entrada: new Date("2023-01-24"),
    hora: "13:20",
    sistema: "Sistema C",
    serventia: "Serventia Oeste",
    codigo: "COD-015",
    prazo: "4 dias",
    ultimaAtualizacao: new Date("2023-01-28"),
    responsavel: "Gustavo Henrique",
    diasAtras: 0,
    title: "Problema com gráficos",
    description: "Gráficos não estão sendo exibidos",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-24"),
    updatedAt: new Date("2023-01-28"),
  },
  {
    id: "16",
    protocolo: "20230016",
    entrada: new Date("2023-01-25"),
    hora: "10:10",
    sistema: "Sistema A",
    serventia: "Serventia Central",
    codigo: "COD-016",
    prazo: "5 dias",
    ultimaAtualizacao: new Date("2023-01-30"),
    responsavel: "Daniela Silva",
    diasAtras: 0,
    title: "Exportação de dados",
    description: "Exportar dados para formato CSV",
    status: "closed",
    priority: "low",
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2023-01-30"),
  },
  {
    id: "17",
    protocolo: "20230017",
    entrada: new Date("2023-01-26"),
    hora: "15:35",
    sistema: "Sistema B",
    serventia: "Serventia Norte",
    codigo: "COD-017",
    prazo: "3 dias",
    ultimaAtualizacao: new Date("2023-01-29"),
    responsavel: "Eduardo Rocha",
    diasAtras: 0,
    title: "Problema com login",
    description: "Erro ao tentar fazer login",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-26"),
    updatedAt: new Date("2023-01-29"),
  },
  {
    id: "18",
    protocolo: "20230018",
    entrada: new Date("2023-01-27"),
    hora: "09:50",
    sistema: "Sistema C",
    serventia: "Serventia Sul",
    codigo: "COD-018",
    prazo: "6 dias",
    ultimaAtualizacao: new Date("2023-02-02"),
    responsavel: "Beatriz Almeida",
    diasAtras: 0,
    title: "Atualização de permissões",
    description: "Ajustar permissões de usuários",
    status: "in-progress",
    priority: "high",
    createdAt: new Date("2023-01-27"),
    updatedAt: new Date("2023-02-02"),
  },
  {
    id: "19",
    protocolo: "20230019",
    entrada: new Date("2023-01-28"),
    hora: "14:05",
    sistema: "Sistema A",
    serventia: "Serventia Leste",
    codigo: "COD-019",
    prazo: "2 dias",
    ultimaAtualizacao: new Date("2023-01-30"),
    responsavel: "Rafael Carvalho",
    diasAtras: 0,
    title: "Erro na visualização",
    description: "Dados não estão sendo exibidos corretamente",
    status: "closed",
    priority: "low",
    createdAt: new Date("2023-01-28"),
    updatedAt: new Date("2023-01-30"),
  },
  {
    id: "20",
    protocolo: "20230020",
    entrada: new Date("2023-01-29"),
    hora: "11:25",
    sistema: "Sistema B",
    serventia: "Serventia Oeste",
    codigo: "COD-020",
    prazo: "4 dias",
    ultimaAtualizacao: new Date("2023-02-02"),
    responsavel: "Vanessa Oliveira",
    diasAtras: 0,
    title: "Problema com upload",
    description: "Não está conseguindo fazer upload de arquivos",
    status: "open",
    priority: "medium",
    createdAt: new Date("2023-01-29"),
    updatedAt: new Date("2023-02-02"),
  }
];